import type { PhraseSeed } from "./types";

/**
 * 標準問題。全て自作の自然な日本語(CONTENT_GUIDELINES.md 参照)。
 * Tier 帯域: micro 2〜4 / short 5〜7 / standard 8〜12 / long 13モーラ以上
 * (DECISIONS.md D-003, D-040でmicroを追加)
 */
export const PHRASE_SEEDS: readonly PhraseSeed[] = [
  // ---- 追加分(MICRO, D-040: 寿司打を参考にした単語レベルの短さ) ----
  { id: "word_0001", displayText: "犬", readingKana: "いぬ", tier: "micro", category: "単語" },
  { id: "word_0002", displayText: "猫", readingKana: "ねこ", tier: "micro", category: "単語" },
  { id: "word_0003", displayText: "花", readingKana: "はな", tier: "micro", category: "単語" },
  { id: "word_0004", displayText: "空", readingKana: "そら", tier: "micro", category: "単語" },
  { id: "word_0005", displayText: "海", readingKana: "うみ", tier: "micro", category: "単語" },
  { id: "word_0006", displayText: "山", readingKana: "やま", tier: "micro", category: "単語" },
  { id: "word_0007", displayText: "星", readingKana: "ほし", tier: "micro", category: "単語" },
  { id: "word_0008", displayText: "月", readingKana: "つき", tier: "micro", category: "単語" },
  { id: "word_0009", displayText: "水", readingKana: "みず", tier: "micro", category: "単語" },
  { id: "word_0010", displayText: "雲", readingKana: "くも", tier: "micro", category: "単語" },
  { id: "word_0011", displayText: "風", readingKana: "かぜ", tier: "micro", category: "単語" },
  { id: "word_0012", displayText: "雨", readingKana: "あめ", tier: "micro", category: "単語" },
  { id: "word_0013", displayText: "雪", readingKana: "ゆき", tier: "micro", category: "単語" },
  { id: "word_0014", displayText: "鳥", readingKana: "とり", tier: "micro", category: "単語" },
  { id: "word_0015", displayText: "魚", readingKana: "さかな", tier: "micro", category: "単語" },
  { id: "word_0016", displayText: "車", readingKana: "くるま", tier: "micro", category: "単語" },
  { id: "word_0017", displayText: "電話", readingKana: "でんわ", tier: "micro", category: "単語" },
  { id: "word_0018", displayText: "時計", readingKana: "とけい", tier: "micro", category: "単語" },
  { id: "word_0019", displayText: "桜", readingKana: "さくら", tier: "micro", category: "単語" },
  { id: "word_0020", displayText: "財布", readingKana: "さいふ", tier: "micro", category: "単語" },
  { id: "word_0021", displayText: "音楽", readingKana: "おんがく", tier: "micro", category: "単語" },
  { id: "word_0022", displayText: "携帯", readingKana: "けいたい", tier: "micro", category: "単語" },
  { id: "word_0023", displayText: "鉛筆", readingKana: "えんぴつ", tier: "micro", category: "単語" },
  { id: "word_0024", displayText: "教室", readingKana: "きょうしつ", tier: "micro", category: "単語" },

  // ---- 追加分(MICRO 2, D-042: 単語をさらに追加) ----
  { id: "word_0025", displayText: "本", readingKana: "ほん", tier: "micro", category: "単語" },
  { id: "word_0026", displayText: "傘", readingKana: "かさ", tier: "micro", category: "単語" },
  { id: "word_0027", displayText: "机", readingKana: "つくえ", tier: "micro", category: "単語" },
  { id: "word_0028", displayText: "窓", readingKana: "まど", tier: "micro", category: "単語" },
  { id: "word_0029", displayText: "鍵", readingKana: "かぎ", tier: "micro", category: "単語" },
  { id: "word_0030", displayText: "靴", readingKana: "くつ", tier: "micro", category: "単語" },
  { id: "word_0031", displayText: "帽子", readingKana: "ぼうし", tier: "micro", category: "単語" },
  { id: "word_0032", displayText: "手紙", readingKana: "てがみ", tier: "micro", category: "単語" },
  { id: "word_0033", displayText: "眼鏡", readingKana: "めがね", tier: "micro", category: "単語" },
  { id: "word_0034", displayText: "果物", readingKana: "くだもの", tier: "micro", category: "単語" },
  { id: "word_0035", displayText: "野菜", readingKana: "やさい", tier: "micro", category: "単語" },
  { id: "word_0036", displayText: "卵", readingKana: "たまご", tier: "micro", category: "単語" },
  { id: "word_0037", displayText: "氷", readingKana: "こおり", tier: "micro", category: "単語" },
  { id: "word_0038", displayText: "虹", readingKana: "にじ", tier: "micro", category: "単語" },
  { id: "word_0039", displayText: "春", readingKana: "はる", tier: "micro", category: "単語" },
  { id: "word_0040", displayText: "夏", readingKana: "なつ", tier: "micro", category: "単語" },

  // ---- 追加分(MICRO 3, D-043: 単語をさらに拡充) ----
  { id: "word_0041", displayText: "秋", readingKana: "あき", tier: "micro", category: "単語" },
  { id: "word_0042", displayText: "冬", readingKana: "ふゆ", tier: "micro", category: "単語" },
  { id: "word_0043", displayText: "森", readingKana: "もり", tier: "micro", category: "単語" },
  { id: "word_0044", displayText: "石", readingKana: "いし", tier: "micro", category: "単語" },
  { id: "word_0045", displayText: "土", readingKana: "つち", tier: "micro", category: "単語" },
  { id: "word_0046", displayText: "家", readingKana: "いえ", tier: "micro", category: "単語" },
  { id: "word_0047", displayText: "庭", readingKana: "にわ", tier: "micro", category: "単語" },
  { id: "word_0048", displayText: "池", readingKana: "いけ", tier: "micro", category: "単語" },
  { id: "word_0049", displayText: "橋", readingKana: "はし", tier: "micro", category: "単語" },
  { id: "word_0050", displayText: "駅", readingKana: "えき", tier: "micro", category: "単語" },
  { id: "word_0051", displayText: "道", readingKana: "みち", tier: "micro", category: "単語" },
  { id: "word_0052", displayText: "店", readingKana: "みせ", tier: "micro", category: "単語" },
  { id: "word_0053", displayText: "服", readingKana: "ふく", tier: "micro", category: "単語" },
  { id: "word_0054", displayText: "皿", readingKana: "さら", tier: "micro", category: "単語" },
  { id: "word_0055", displayText: "針", readingKana: "はり", tier: "micro", category: "単語" },
  { id: "word_0056", displayText: "缶", readingKana: "かん", tier: "micro", category: "単語" },
  { id: "word_0057", displayText: "袋", readingKana: "ふくろ", tier: "micro", category: "単語" },
  { id: "word_0058", displayText: "布団", readingKana: "ふとん", tier: "micro", category: "単語" },
  { id: "word_0059", displayText: "銀行", readingKana: "ぎんこう", tier: "micro", category: "単語" },
  { id: "word_0060", displayText: "公園", readingKana: "こうえん", tier: "micro", category: "単語" },

  // ---- 設計書サンプル由来(TYPE_BURST_Japanese_Phrase_Samples.json) ----
  { id: "daily_0001", displayText: "空が明るくなる", readingKana: "そらがあかるくなる", tier: "standard", category: "日常" },
  { id: "daily_0002", displayText: "音が聞こえる", readingKana: "おとがきこえる", tier: "short", category: "日常" },
  { id: "daily_0003", displayText: "本を読みます", readingKana: "ほんをよみます", tier: "short", category: "日常" },
  { id: "work_0001", displayText: "資料を確認する", readingKana: "しりょうをかくにんする", tier: "standard", category: "仕事" },
  { id: "work_0002", displayText: "会議を始めます", readingKana: "かいぎをはじめます", tier: "standard", category: "仕事" },
  { id: "work_0003", displayText: "予定を共有する", readingKana: "よていをきょうゆうする", tier: "standard", category: "仕事" },
  { id: "school_0001", displayText: "ノートを見直す", readingKana: "のーとをみなおす", tier: "standard", category: "学校" },
  { id: "school_0002", displayText: "授業の準備をする", readingKana: "じゅぎょうのじゅんびをする", tier: "standard", category: "学校" },
  { id: "move_0001", displayText: "電車が駅に到着した", readingKana: "でんしゃがえきにとうちゃくした", tier: "long", category: "移動" },
  { id: "move_0002", displayText: "少し早めに出発する", readingKana: "すこしはやめにしゅっぱつする", tier: "long", category: "移動" },
  { id: "action_0001", displayText: "明日の予定を決める", readingKana: "あしたのよていをきめる", tier: "standard", category: "行動" },
  { id: "action_0002", displayText: "忘れ物に気をつける", readingKana: "わすれものにきをつける", tier: "standard", category: "行動" },
  { id: "action_0003", displayText: "新しい方法を試してみる", readingKana: "あたらしいほうほうをためしてみる", tier: "long", category: "行動" },
  { id: "positive_0001", displayText: "落ち着いて入力する", readingKana: "おちついてにゅうりょくする", tier: "standard", category: "前向き" },
  { id: "positive_0002", displayText: "最後まで正確に打ち切る", readingKana: "さいごまでせいかくにうちきる", tier: "long", category: "前向き" },
  { id: "positive_0003", displayText: "自分のペースで進める", readingKana: "じぶんのぺーすですすめる", tier: "standard", category: "前向き" },
  { id: "season_0001", displayText: "春の風が吹いている", readingKana: "はるのかぜがふいている", tier: "standard", category: "季節" },
  { id: "season_0002", displayText: "雨の音が静かに続く", readingKana: "あめのおとがしずかにつづく", tier: "long", category: "季節" },
  { id: "food_0001", displayText: "温かいご飯を食べる", readingKana: "あたたかいごはんをたべる", tier: "standard", category: "食事" },
  { id: "talk_0001", displayText: "あとで連絡します", readingKana: "あとでれんらくします", tier: "standard", category: "会話" },

  // ---- 追加分(SHORT) ----
  { id: "season_0003", displayText: "空が晴れる", readingKana: "そらがはれる", tier: "short", category: "季節" },
  { id: "food_0002", displayText: "水を飲む", readingKana: "みずをのむ", tier: "short", category: "食事" },
  { id: "daily_0004", displayText: "声が届く", readingKana: "こえがとどく", tier: "short", category: "日常" },
  { id: "action_0004", displayText: "手を洗う", readingKana: "てをあらう", tier: "short", category: "行動" },
  { id: "move_0003", displayText: "道を渡る", readingKana: "みちをわたる", tier: "short", category: "移動" },
  { id: "season_0004", displayText: "朝日がのぼる", readingKana: "あさひがのぼる", tier: "short", category: "季節" },
  { id: "talk_0002", displayText: "夢を語る", readingKana: "ゆめをかたる", tier: "short", category: "会話" },
  { id: "school_0003", displayText: "席に着く", readingKana: "せきにつく", tier: "short", category: "学校" },

  // ---- 追加分(SHORT 2, D-042) ----
  { id: "season_0007", displayText: "風が吹く", readingKana: "かぜがふく", tier: "short", category: "季節" },
  { id: "season_0008", displayText: "花が咲く", readingKana: "はながさく", tier: "short", category: "季節" },
  { id: "daily_0009", displayText: "目が覚める", readingKana: "めがさめる", tier: "short", category: "日常" },
  { id: "school_0007", displayText: "席を立つ", readingKana: "せきをたつ", tier: "short", category: "学校" },
  { id: "daily_0010", displayText: "本を閉じる", readingKana: "ほんをとじる", tier: "short", category: "日常" },
  { id: "talk_0004", displayText: "電話に出る", readingKana: "でんわにでる", tier: "short", category: "会話" },
  { id: "work_0007", displayText: "荷物を運ぶ", readingKana: "にもつをはこぶ", tier: "short", category: "仕事" },
  { id: "action_0007", displayText: "靴を履く", readingKana: "くつをはく", tier: "short", category: "行動" },
  { id: "season_0009", displayText: "傘を差す", readingKana: "かさをさす", tier: "short", category: "季節" },
  { id: "school_0008", displayText: "席に座る", readingKana: "せきにすわる", tier: "short", category: "学校" },
  { id: "move_0007", displayText: "電車を待つ", readingKana: "でんしゃをまつ", tier: "short", category: "移動" },
  { id: "talk_0005", displayText: "笑顔で話す", readingKana: "えがおではなす", tier: "short", category: "会話" },
  { id: "positive_0008", displayText: "空を見上げる", readingKana: "そらをみあげる", tier: "short", category: "前向き" },
  { id: "action_0008", displayText: "手を伸ばす", readingKana: "てをのばす", tier: "short", category: "行動" },
  { id: "daily_0011", displayText: "目を閉じる", readingKana: "めをとじる", tier: "short", category: "日常" },

  // ---- 追加分(SHORT 3, D-043) ----
  { id: "season_0014", displayText: "雪が降る", readingKana: "ゆきがふる", tier: "short", category: "季節" },
  { id: "daily_0014", displayText: "鍵をかける", readingKana: "かぎをかける", tier: "short", category: "日常" },
  { id: "action_0011", displayText: "窓を閉める", readingKana: "まどをしめる", tier: "short", category: "行動" },
  { id: "work_0011", displayText: "会議に出る", readingKana: "かいぎにでる", tier: "short", category: "仕事" },
  { id: "move_0011", displayText: "橋を渡る", readingKana: "はしをわたる", tier: "short", category: "移動" },
  { id: "talk_0007", displayText: "挨拶をする", readingKana: "あいさつをする", tier: "short", category: "会話" },
  { id: "school_0012", displayText: "宿題をする", readingKana: "しゅくだいをする", tier: "short", category: "学校" },
  { id: "food_0010", displayText: "パンを焼く", readingKana: "ぱんをやく", tier: "short", category: "食事" },
  { id: "positive_0012", displayText: "笑顔になる", readingKana: "えがおになる", tier: "short", category: "前向き" },
  { id: "daily_0015", displayText: "鏡を見る", readingKana: "かがみをみる", tier: "short", category: "日常" },
  { id: "action_0012", displayText: "皿を洗う", readingKana: "さらをあらう", tier: "short", category: "行動" },
  { id: "season_0015", displayText: "星が光る", readingKana: "ほしがひかる", tier: "short", category: "季節" },
  { id: "move_0012", displayText: "駅に着く", readingKana: "えきにつく", tier: "short", category: "移動" },
  { id: "work_0012", displayText: "資料を配る", readingKana: "しりょうをくばる", tier: "short", category: "仕事" },
  { id: "talk_0008", displayText: "名前を呼ぶ", readingKana: "なまえをよぶ", tier: "short", category: "会話" },

  // ---- 追加分(STANDARD) ----
  { id: "daily_0005", displayText: "今日は早く帰ります", readingKana: "きょうははやくかえります", tier: "standard", category: "日常" },
  { id: "daily_0006", displayText: "窓を開けて風を通す", readingKana: "まどをあけてかぜをとおす", tier: "standard", category: "日常" },
  { id: "move_0004", displayText: "駅まで歩いて向かう", readingKana: "えきまであるいてむかう", tier: "standard", category: "移動" },
  { id: "food_0003", displayText: "昼ごはんを食べに行く", readingKana: "ひるごはんをたべにいく", tier: "standard", category: "食事" },
  { id: "work_0004", displayText: "メモを取りながら聞く", readingKana: "めもをとりながらきく", tier: "standard", category: "仕事" },
  { id: "school_0004", displayText: "質問に手を挙げる", readingKana: "しつもんにてをあげる", tier: "standard", category: "学校" },
  { id: "action_0005", displayText: "部屋を少し片付ける", readingKana: "へやをすこしかたづける", tier: "standard", category: "行動" },
  { id: "move_0005", displayText: "次の駅で乗り換える", readingKana: "つぎのえきでのりかえる", tier: "standard", category: "移動" },
  { id: "talk_0003", displayText: "友達と少し話す", readingKana: "ともだちとすこしはなす", tier: "standard", category: "会話" },
  { id: "food_0004", displayText: "熱いお茶を飲む", readingKana: "あついおちゃをのむ", tier: "standard", category: "食事" },
  { id: "positive_0004", displayText: "深呼吸して落ち着く", readingKana: "しんこきゅうしておちつく", tier: "standard", category: "前向き" },
  { id: "work_0005", displayText: "今日の目標を書く", readingKana: "きょうのもくひょうをかく", tier: "standard", category: "仕事" },
  { id: "daily_0007", displayText: "買い物のリストを作る", readingKana: "かいもののりすとをつくる", tier: "standard", category: "日常" },
  { id: "school_0005", displayText: "図書館で本を借りる", readingKana: "としょかんでほんをかりる", tier: "standard", category: "学校" },
  { id: "season_0005", displayText: "夜空の星を眺める", readingKana: "よぞらのほしをながめる", tier: "standard", category: "季節" },
  { id: "positive_0005", displayText: "小さな一歩を重ねる", readingKana: "ちいさないっぽをかさねる", tier: "standard", category: "前向き" },

  // ---- 追加分(STANDARD 2, D-042) ----
  { id: "food_0006", displayText: "朝ごはんを食べる", readingKana: "あさごはんをたべる", tier: "standard", category: "食事" },
  { id: "daily_0012", displayText: "新しい靴を買う", readingKana: "あたらしいくつをかう", tier: "standard", category: "日常" },
  { id: "talk_0006", displayText: "友達に手紙を書く", readingKana: "ともだちにてがみをかく", tier: "standard", category: "会話" },
  { id: "daily_0013", displayText: "明日の天気を調べる", readingKana: "あしたのてんきをしらべる", tier: "standard", category: "日常" },
  { id: "action_0009", displayText: "部屋の掃除を終える", readingKana: "へやのそうじをおえる", tier: "standard", category: "行動" },
  { id: "move_0008", displayText: "会社まで自転車で行く", readingKana: "かいしゃまでじてんしゃでいく", tier: "standard", category: "移動" },
  { id: "food_0007", displayText: "冷たい水を飲み干す", readingKana: "つめたいみずをのみほす", tier: "standard", category: "食事" },
  { id: "action_0010", displayText: "週末に映画を見る", readingKana: "しゅうまつにえいがをみる", tier: "standard", category: "行動" },
  { id: "school_0009", displayText: "図書館で静かに読む", readingKana: "としょかんでしずかによむ", tier: "standard", category: "学校" },
  { id: "work_0008", displayText: "仕事の合間に休む", readingKana: "しごとのあいまにやすむ", tier: "standard", category: "仕事" },
  { id: "season_0010", displayText: "夕方に散歩をする", readingKana: "ゆうがたにさんぽをする", tier: "standard", category: "季節" },
  { id: "school_0010", displayText: "単語を覚える", readingKana: "たんごをおぼえる", tier: "standard", category: "学校" },
  { id: "season_0011", displayText: "静かな夜に星を見る", readingKana: "しずかなよるにほしをみる", tier: "standard", category: "季節" },
  { id: "food_0008", displayText: "お茶を用意する", readingKana: "おちゃをよういする", tier: "standard", category: "食事" },
  { id: "work_0009", displayText: "予定を確認する", readingKana: "よていをかくにんする", tier: "standard", category: "仕事" },

  // ---- 追加分(STANDARD 3, D-043) ----
  { id: "daily_0016", displayText: "朝早く目を覚ます", readingKana: "あさはやくめをさます", tier: "standard", category: "日常" },
  { id: "work_0013", displayText: "会議室に集まる", readingKana: "かいぎしつにあつまる", tier: "standard", category: "仕事" },
  { id: "school_0013", displayText: "黒板の字を写す", readingKana: "こくばんのじをうつす", tier: "standard", category: "学校" },
  { id: "move_0013", displayText: "バス停で友達と会う", readingKana: "ばすていでともだちとあう", tier: "standard", category: "移動" },
  { id: "food_0011", displayText: "野菜をよく洗う", readingKana: "やさいをよくあらう", tier: "standard", category: "食事" },
  { id: "action_0013", displayText: "荷物を棚に置く", readingKana: "にもつをたなにおく", tier: "standard", category: "行動" },
  { id: "season_0016", displayText: "秋の空を見上げる", readingKana: "あきのそらをみあげる", tier: "standard", category: "季節" },
  { id: "positive_0013", displayText: "焦らず進める", readingKana: "あせらずすすめる", tier: "standard", category: "前向き" },
  { id: "talk_0009", displayText: "相手の話を聞く", readingKana: "あいてのはなしをきく", tier: "standard", category: "会話" },
  { id: "work_0014", displayText: "書類にサインする", readingKana: "しょるいにさいんする", tier: "standard", category: "仕事" },
  { id: "daily_0017", displayText: "洗濯物を畳む", readingKana: "せんたくものをたたむ", tier: "standard", category: "日常" },
  { id: "school_0014", displayText: "先生に質問する", readingKana: "せんせいにしつもんする", tier: "standard", category: "学校" },
  { id: "food_0012", displayText: "果物を切って食べる", readingKana: "くだものをきってたべる", tier: "standard", category: "食事" },
  { id: "move_0014", displayText: "信号が青に変わる", readingKana: "しんごうがあおにかわる", tier: "standard", category: "移動" },
  { id: "season_0017", displayText: "冬の朝は空気が澄む", readingKana: "ふゆのあさはくうきがすむ", tier: "standard", category: "季節" },

  // ---- 追加分(LONG) ----
  { id: "action_0006", displayText: "新しい方法をみんなで試してみる", readingKana: "あたらしいほうほうをみんなでためしてみる", tier: "long", category: "行動" },
  { id: "daily_0008", displayText: "今日は少し早めに寝ようと思う", readingKana: "きょうはすこしはやめにねようとおもう", tier: "long", category: "日常" },
  { id: "season_0006", displayText: "窓の外の景色をゆっくり眺める", readingKana: "まどのそとのけしきをゆっくりながめる", tier: "long", category: "季節" },
  { id: "work_0006", displayText: "明日の会議の資料をまとめておく", readingKana: "あしたのかいぎのしりょうをまとめておく", tier: "long", category: "仕事" },
  { id: "move_0006", displayText: "駅前のパン屋に寄ってから帰る", readingKana: "えきまえのぱんやによってからかえる", tier: "long", category: "移動" },
  { id: "food_0005", displayText: "温かいスープを飲んで一息つく", readingKana: "あたたかいすーぷをのんでひといきつく", tier: "long", category: "食事" },
  { id: "positive_0006", displayText: "練習を続ければ必ず速くなる", readingKana: "れんしゅうをつづければかならずはやくなる", tier: "long", category: "前向き" },
  { id: "school_0006", displayText: "授業の内容を友達と確認する", readingKana: "じゅぎょうのないようをともだちとかくにんする", tier: "long", category: "学校" },
  { id: "positive_0007", displayText: "静かな朝に本を開く", readingKana: "しずかなあさにほんをひらく", tier: "long", category: "前向き" },

  // ---- 追加分(LONG 2, D-042) ----
  { id: "positive_0009", displayText: "休みの日はゆっくり体を休める", readingKana: "やすみのひはゆっくりからだをやすめる", tier: "long", category: "前向き" },
  { id: "move_0009", displayText: "電車の窓から夕日を眺める", readingKana: "でんしゃのまどからゆうひをながめる", tier: "long", category: "移動" },
  { id: "positive_0010", displayText: "忙しい一日の終わりに深呼吸する", readingKana: "いそがしいいちにちのおわりにしんこきゅうする", tier: "long", category: "前向き" },
  { id: "season_0012", displayText: "雨の日でも傘をさして出かける", readingKana: "あめのひでもかさをさしてでかける", tier: "long", category: "季節" },
  { id: "positive_0011", displayText: "新しい仕事にも少しずつ慣れてきた", readingKana: "あたらしいしごとにもすこしずつなれてきた", tier: "long", category: "前向き" },
  { id: "move_0010", displayText: "駅前の広場でみんなで待ち合わせる", readingKana: "えきまえのひろばでみんなでまちあわせる", tier: "long", category: "移動" },
  { id: "food_0009", displayText: "台所で夕食の準備を始める", readingKana: "だいどころでゆうしょくのじゅんびをはじめる", tier: "long", category: "食事" },
  { id: "school_0011", displayText: "静かな図書室で集中して勉強する", readingKana: "しずかなとしょしつでしゅうちゅうしてべんきょうする", tier: "long", category: "学校" },
  { id: "season_0013", displayText: "冷たい風が窓の隙間から入ってくる", readingKana: "つめたいかぜがまどのすきまからはいってくる", tier: "long", category: "季節" },
  { id: "work_0010", displayText: "会議室に資料をすべて運んでおく", readingKana: "かいぎしつにしりょうをすべてはこんでおく", tier: "long", category: "仕事" },

  // ---- 追加分(LONG 3, D-043) ----
  { id: "move_0015", displayText: "電車が遅れて少し焦った", readingKana: "でんしゃがおくれてすこしあせった", tier: "long", category: "移動" },
  { id: "season_0018", displayText: "夏の夜に虫の声を聞く", readingKana: "なつのよるにむしのこえをきく", tier: "long", category: "季節" },
  { id: "work_0015", displayText: "新しい企画について話し合う", readingKana: "あたらしいきかくについてはなしあう", tier: "long", category: "仕事" },
  { id: "positive_0014", displayText: "失敗しても諦めずにもう一度挑戦する", readingKana: "しっぱいしてもあきらめずにもういちどちょうせんする", tier: "long", category: "前向き" },
  { id: "daily_0018", displayText: "掃除をしたら部屋が広く感じた", readingKana: "そうじをしたらへやがひろくかんじた", tier: "long", category: "日常" },
  { id: "school_0015", displayText: "難しい問題を友達と一緒に解く", readingKana: "むずかしいもんだいをともだちといっしょにとく", tier: "long", category: "学校" },
  { id: "food_0013", displayText: "家族みんなで晩ごはんを食べる", readingKana: "かぞくみんなでばんごはんをたべる", tier: "long", category: "食事" },
  { id: "move_0016", displayText: "目的地までもう少しで到着する", readingKana: "もくてきちまでもうすこしでとうちゃくする", tier: "long", category: "移動" },
  { id: "season_0019", displayText: "涼しい風が部屋の中を通り抜ける", readingKana: "すずしいかぜがへやのなかをとおりぬける", tier: "long", category: "季節" },
  { id: "positive_0015", displayText: "毎日少しずつ上達していく", readingKana: "まいにちすこしずつじょうたつしていく", tier: "long", category: "前向き" },
];

/**
 * 妨害ブロック用の文章(無属性ブロックに表示)。
 * DUEL / GHOST 実装時に使用する。
 */
export const GARBAGE_PHRASE_SEEDS: readonly PhraseSeed[] = [
  { id: "garbage_0001", displayText: "焦らず確実に入力する", readingKana: "あせらずかくじつににゅうりょくする", tier: "long", category: "妨害" },
  { id: "garbage_0002", displayText: "最後まで正確に打つ", readingKana: "さいごまでせいかくにうつ", tier: "standard", category: "妨害" },
  { id: "garbage_0003", displayText: "目の前の文章に集中する", readingKana: "めのまえのぶんしょうにしゅうちゅうする", tier: "long", category: "妨害" },
  { id: "garbage_0004", displayText: "慌てず一文字ずつ進める", readingKana: "あわてずひともじずつすすめる", tier: "long", category: "妨害" },
  { id: "garbage_0005", displayText: "指先に意識を向ける", readingKana: "ゆびさきにいしきをむける", tier: "standard", category: "妨害" },
  { id: "garbage_0006", displayText: "姿勢を正して構える", readingKana: "しせいをただしてかまえる", tier: "standard", category: "妨害" },
  { id: "garbage_0007", displayText: "深呼吸してから打つ", readingKana: "しんこきゅうしてからうつ", tier: "standard", category: "妨害" },
  { id: "garbage_0008", displayText: "リズムを崩さず打ち続ける", readingKana: "りずむをくずさずうちつづける", tier: "long", category: "妨害" },
];
